language: node_js

services:
  - redis-server
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE tests;'

node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
  - "8"

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run test
  - npm run build